version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/xarillian.com
  - source: xarillian.com.conf
    destination /etc/nginx/sites-available/xarillian.com
hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_application.sh
      timeout: 900
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu
